### ISSUE TITLE
정렬기능(html 버튼추가, js 파일 추가)

### ISSUE THREAD

**Issue by minjun0702** [hyeonseol00/Movie-Collection_Team-Dinosaur#10]
정렬기능(html 버튼추가, js 파일 추가)

**Comment by hyeonseol00** [comment]
정렬 기능이 아니라 리뷰 삭제 기능 완료 후 dev에 병합되었습니다.
기존 브랜치가 닫혀 이슈도 닫으니 새로 이슈 등록해주시기 바랍니다.
